modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="doom"
version="${file.jarVersion}"
displayName="Doom Mod"
logoFile="doomlogo.png"
authors="AzureDoomC" 
description='''
Adds Doom into Minecraft
'''
[[dependencies.doom]]
    modId="curios"
    mandatory=true
   	versionRange="[1.16.3-4.0.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.doom]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.30,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.geckolib3]]
    modId="forge"
    mandatory=true 
    versionRange="[36.1.1,)" 
    ordering="NONE"
    side="BOTH"