modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/AzureDoom/Doom-Crucible/issues"
logoFile="doomlogo.png"
[[mods]] 
modId="doomweapon"
version="${file.jarVersion}" 
displayName="Azuredooms Doom Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/doom-items-mod" 
authors="AzureDoomC" 
credits="Thanks to Narial/ulnight for the awesome Sword/Axe and textures! Also Credit to C-Legend for the tools and armor textures! Credit to Marctron for the new armor textures!"
description='''
Adds Doom into Minecraft
'''
[[dependencies.doomweapon]]
    modId="curios"
    mandatory=true
   	versionRange="[FORGE-1.15.2-2.0.2.6,)"
    ordering="NONE"
    side="BOTH"